Hello Microverse Project: feature branch
78fatemanazari/Hello-Project pull request #1
Opened 2023-05-30 20:22 UTC by 78fatemanazari

Description:
In this project, you will set up a "Hello world" repository. No complex coding is required for this exercise. Your goal here is to master all of the tools and best practices you learned about in previous steps. You will be using them in all Microverse projects and most likely in your future job as well, so it is important to know them! You will also get your first code review. This is also a process that will be used in all Microverse projects.

Requirements:
1. Remember to document your work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).
2. Create a new GitHub repo.
3. Create a new branch according to the [GitHub flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md) rules.
4. Add a .gitignore file.
5. Add node_modules to gitignore file.
6. Set up [a linter for HTML and CSS](https://github.com/microverseinc/linters-config) and make sure that any files that are not relevant are ignored by git.
7. Add a descriptive README file to your project - please use [this template](https://github.com/microverseinc/readme-template) but remember to customize it to your project.
8. Add 3 files (each one in a separate commit):
            1. html file that includes a header with the text "Hello Microverse!". Use h1 tag for that.
            2. css file that includes one class with styles for your header (make it in your favorite color).
            3. test.md file with the text "This file should be ignored by git".
9. Make sure that the last file is actually ignored by git and is not present in your GitHub repository.
10. Open a pull request.

2023-05-30 20:50 UTC, AdnanOlarmmi requested changes
Hi @78fatemanazari, 

This is Adnan Is-haq, your beloved code reviewer,

You've done a very good job so far, but a few things still need to be worked on before moving on to the next project, but you're so close!

![You're Almost there, funny one eyed alien](https://user-images.githubusercontent.com/41163571/217957948-6d8d9f33-125c-4724-954f-330eed60533c.gif)

## Highlights
- Nice setup.
- Linters are passing.

## Required Changes ♻️
Please refer to this article: please read it and apply it in your work from now on: [Professional repo - basic rules](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md);
- [ ] I kindly suggest that you name your branch name after a feature or action e.g `created-Hello-Microverse`. Please kindly check [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) for how to rename your branch or you can create a new feature branch and pull request and use the name of a feature for your branch e.g created-Hello-Microverse for your branch. Kindly ensure to use a very appropriate branch name, `feature-branch` is too vague 🙂. When you create a new branch, ensure you have a link to this pull request in the new pull request to enable the new reviewer follow through with the previous review.

- [ ] Kindly complete your readme section, you can follow the readme in [this repo](https://github.com/AdnanOlarmmi/Technopreneur) for inspiration.

- [ ] Kindly add at least two future features to enable anyone checking your profile and repo know how active you are. 😉 

- [ ] Please add one or two future features as required, this will make your readme look professional and inform potential overlooker of you future developments.


- [ ] To reiterate Kindly use a descriptive branch name giving a one to two words summary of what you've done in this milestone, for this particular example may "hello-microverse" for some, maybe you've implemented a mobile menu you'd say "mobile-menu".

_Check the comments under the review._

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-30 20:50 UTC, AdnanOlarmmi commented on README.md
- [ ] Kindly complete your readme section, you can follow the readme in [this repo](https://github.com/AdnanOlarmmi/Technopreneur) for inspiration.
Kindly fill all of the required sections, except live demo since you might not deploy this project.

2023-05-30 20:50 UTC, AdnanOlarmmi commented on .gitignore
> +test.md
- [ ] You have successfully ignored the test.md file in your .gitignore file, but maybe because you pushed before ignoring the file... The file is already in your repo, kindly delete it

2023-05-30 20:50 UTC, AdnanOlarmmi commented on README.md
> +> Mention all of the collaborators of this project.
- [ ] please, remove all gray sentences like this, they are just there to direct you, like give you a hint of what to do under each section.

2023-05-30 20:50 UTC, AdnanOlarmmi commented on README.md
> +    <li><a href="https://reactjs.org/">HTML & CSS</a></li>
- [ ] your project wasn't created with React, kindly add the technologies you used.

2023-05-30 20:50 UTC, AdnanOlarmmi commented on MIT.md
![Screenshot_20230530-213049](https://github.com/78fatemanazari/Hello-Project/assets/41163571/4c389375-205f-466f-ae4a-184fc5599596)
- [ ] You have a license file but the link isn't working properly, this is because the link used is different from the file name, the file name is MIT.md and the link is /LICENSE, it's either you change the file name or the link name, then afterwards confirm if it is working properly before submitting for re-review.

2023-05-30 20:50 UTC, AdnanOlarmmi commented on README.md
> +_NOTE: we recommend using the [MIT license](https://choosealicense.com/licenses/mit/) - you can set it up quickly by [using templates available on GitHub](https://docs.github.com/en/communities/setti
- [ ] Kindly remove this italicized phrase, as it is there to give you directions and shouldn't be in your professional repo.

2023-05-31 00:40 UTC, jmonto55 approved these changes
# STATUS: APPROVED 🟢

Hi @78fatemanazari , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![AgreeSealGIF](https://user-images.githubusercontent.com/116701485/232347692-8a213af9-b250-4d2c-a690-7f42d3c630e0.gif)


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-31 07:33 UTC, merged